"""Tablas

Revision ID: fcf7a5b0af96
Revises: 
Create Date: 2022-06-21 16:47:00.688592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf7a5b0af96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_id'), 'grupo', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuenta_id'), 'cuenta', ['id'], unique=False)
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_privacidad', sa.String(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_id'), 'evento', ['id'], unique=False)
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacto_id'), 'contacto', ['id'], unique=False)
    op.create_table('cuenta_grupo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_create', sa.DateTime(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivo_id'), 'archivo', ['id'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_grupo_id'], ['cuenta_grupo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_id'), 'notificacion', ['id'], unique=False)
    op.create_table('reaccion_Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('reaccion', sa.String(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaccion_Post_id'), 'reaccion_Post', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaccion_Post_id'), table_name='reaccion_Post')
    op.drop_table('reaccion_Post')
    op.drop_index(op.f('ix_notificacion_id'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_archivo_id'), table_name='archivo')
    op.drop_table('archivo')
    op.drop_table('post')
    op.drop_table('cuenta_grupo')
    op.drop_index(op.f('ix_contacto_id'), table_name='contacto')
    op.drop_table('contacto')
    op.drop_index(op.f('ix_evento_id'), table_name='evento')
    op.drop_table('evento')
    op.drop_index(op.f('ix_cuenta_id'), table_name='cuenta')
    op.drop_table('cuenta')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_grupo_id'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###